name: Android Build

on: pull_request

jobs:

  build:

    runs-on:

      steps:
        - uses: actions/checkout@v1

        - name: Set Up JDK
          uses: actions/setup-java@v1q
          with:
            java-version: 1.8

        - name: Run Tests
          run: ./gradlew test

        - name: Build Project
          run: ./gradlew assemble
